# -*- coding: utf-8 -*-
"""ILMMAIenrollment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VwoPMGkejCCgWhmWwLXNBBQ7vpGVdSfJ
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install tabula-py
# %pip install JPype1
# %pip install pandas

import tabula
import pandas

url = 'https://hfs.illinois.gov/content/dam/soi/en/web/hfs/sitecollectiondocuments/202507mcoaer.pdf'
tables = tabula.read_pdf(url)
print(type(tables))
print(len(tables))

table = tables[0]
table

tables = tabula.read_pdf(url, pages = 'all')
print(len(tables))

tables

